services:
  pdf-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pdf-service
    volumes:
      - files_storage:/data_files_storage
    env_file:
      - .env
    command: ["python", "main.py"]

volumes:
  files_storage:
    name: files_storage
    external: true

networks:
  default:
    name: shared-net
    external: true
